---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: amerisourcebergenapp
 labels:
  app: amerisourcebergenapp
spec:
 replicas: 1
 selector:
  matchLabels:
   app: amerisourcebergenapp
 template:
  metadata: 
   labels:
    app: amerisourcebergenapp
  spec:
   containers:
   - name: amerisourcebergenapp
     image: raghukom/devops:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: amerisourcebergenapp
spec:
  type: LoadBalancer
  selector:
    app: amerisourcebergenapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
